site_name: Məşğuliyyətnamə
repo_url: https://github.com/stiermid/mesguliyyetname
edit_uri: edit/master/docs

theme:
  name: terminal
  palette: dark
  features:
    - footer.prev_next
    - revision.date
    - revision.history

nav:
  - Müqəddimə: 'index.md'
  - Bəndlər: 'bendler.md'


plugins:
  - git-revision-date

markdown_extensions:
  - meta
  - footnotes
  - toc:
      permalink: "#"

