site_name: Məşğuliyyətnamə
repo_url: https://github.com/stiermid/mesguliyyetname
edit_uri: edit/master/docs

theme:
  name: terminal
  palette: dark
  features:
    - footer.prev_next
    - revision.date
    - revision.history

nav:
  - Müqəddimə: 'index.md'
  - Bəndlər: 'bendler.md'


plugins:
  - git-revision-date
  - macros
  - rss:
      enabled: true
      rss_feed_enabled: true
      json_feed_enabled: true
      feeds_filenames:
        json_created: feed.json
        json_updated: feed_updated.json
        rss_created: feed.xml
        rss_updated: feed_updated.xml

markdown_extensions:
  - meta
  - footnotes
  - toc:
      permalink: "#"

